// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using UnityEngine;

public class HealthBar
{
	//assume default resolution for scaling elements
	private Health health;
	private Rect healthBar = new Rect(40, 25, 200, 30);
	private Rect healthBarScaled;
	private Rect currentHealthBar;
	private Texture2D healthTexture;
	private Texture2D barTexture;

	public HealthBar(Health health, Rect location, Texture2D barTexture, Texture2D healthTexture)
	{
		this.health = health;
		this.healthBar = location;
		this.barTexture = barTexture;
		this.healthTexture = healthTexture;

		ScaleHealth();

		GUIManager.OnDraw += OnDrawHealth;
		GameManager.resolutionChanged += ScaleHealth;
	}
		
	void OnDrawHealth()
	{
		if(health == null || !health.gameObject.activeSelf)
			return;
		GUI.DrawTexture(healthBarScaled, barTexture);
		currentHealthBar.width = health.f_currentHP / health.fullHP * healthBarScaled.width;
		GUI.DrawTexture(currentHealthBar, healthTexture);
	}

	void ScaleHealth() {
		float xScale = Screen.width / GameManager.screenScale.x;
		float yScale = Screen.height / GameManager.screenScale.y;

		healthBarScaled = new Rect(healthBar);
		healthBarScaled.x *= xScale;
		healthBarScaled.width *= xScale;
		healthBarScaled.y *= yScale;
		healthBarScaled.height *= yScale;
		currentHealthBar = new Rect(healthBarScaled);
	}

	~HealthBar() {
		GUIManager.OnDraw -= OnDrawHealth;
		GameManager.resolutionChanged += ScaleHealth;
	}
}


